spring:
  datasource:
    url: jdbc:mysql://localhost:3306/score_database?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
#    password: xiaoshuai0628
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: score-system
  data:
    redis:
      host: 127.0.0.1
      port: 5050
      password: xs0628
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1s
mybatis-plus:
  type-aliases-package: com.score.system.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*.xml
server:
  port: 12442
  servlet:
    context-path: /score
#  error:
#    whitelabel:
#      enabled: false
#    include-message: always
#    include-binding-errors: always